### ISSUE TITLE
Unable to download pack

### ISSUE THREAD

**Issue by SimplyMedi0cre** [azraerl/serenity#12]
I am unable to download the pack, it keeps failing to download Skyrim SE 0462, I think this is because it needs updating to Skyrim SE 0463

**Comment by azraerl** [comment]
See instructions at https://github.com/azraerl/serenity/issues/8

**Comment by slaughter2012** [comment]
Hi, same issue, serenity can't download se462 enb. I downloaded it from http://enbdev.com/download_mod_tesskyrimse.htm and put it  in the downloads where all the other mods are. Serenity doesn't recognise it's there? All add blockers are off.
![serenity2 no enb download](https://user-images.githubusercontent.com/83192115/138204400-869ae1c4-af9e-454b-8c64-697b60356ee0.jpg)
From the logs
689.71 - Found 1004 total files, 1007 matching filesize
689.77 - Downloading Missing Archives
689.77 - Missing 1 archives
689.77 - Getting Nexus API Key, if a browser appears, please accept
689.77 - Loading server whitelist
690.04 - Loaded permissions for 565 servers and 258 Google Drive files
690.04 - File hash check (-42) 80fc51c51a3537edf59c681e3cd3999f61cf3cef736d769cb89de1afe8e246bc
690.08 - Downloading enbseries_skyrimse_v0462.zip
690.52 - Loading for alternative to nJ59BDEM0qc=
691.09 - Download failed for enbseries_skyrimse_v0462.zip and no upgrade from this download source is possible
691.42 - Hashing Remaining Archives
691.42 - Looking for files to hash
691.45 - Found 1004 total files, 1007 matching filesize
691.53 - Unable to download enbseries_skyrimse_v0462.zip (HTTPDownloader+State|http://enbdev.com/enbseries_skyrimse_v0462.zip)
691.53 - Cannot continue, was unable to download one or more archives
691.53 - File hash check (-42) 80fc51c51a3537edf59c681e3cd3999f61cf3cef736d769cb89de1afe8e246bc
691.53 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
691.79 - File hash check (-42) 80fc51c51a3537edf59c681e3cd3999f61cf3cef736d769cb89de1afe8e246bc
Hope this helps.
And thanks for all your hard work :)
