### ISSUE TITLE
Skyrim Particle Patch - Download

### ISSUE THREAD

**Issue by dicemanproductionz** [azraerl/serenity#25]
Hi there,

Seems to be an issue downloading the Skyrim Particle Patch for ENB SSE

18.46 - Downloading Missing Archives
18.46 - Missing 1 archives
18.46 - Getting Nexus API Key, if a browser appears, please accept
18.47 - Loading server whitelist
18.55 - Loaded permissions for 649 servers and 290 Google Drive files
18.55 - File hash check (-42) 69f0db2e0a25d17dafc6cafd294c7d82f29370ae3baa00ef823479fd5cad9c6e
18.66 - Downloading Skyrim_Particle_Patch_for_ENB-SSE.zip
19.52 - Hashed download is incorrect
19.52 - Loading for alternative to 2MrbjqTtwtg=
19.57 - No alternative for 2MrbjqTtwtg= could be found
19.61 - Hashing Remaining Archives
19.61 - Looking for files to hash
19.65 - Found 1138 total files, 1002 matching filesize
19.74 - Unable to download Skyrim_Particle_Patch_for_ENB-SSE.zip (GoogleDriveDownloader+State|12tL3_kpm_KXlQvQqEnK3zOAl-sm_H3Fw)
19.74 - Cannot continue, was unable to download one or more archives
19.74 - File hash check (-42) 69f0db2e0a25d17dafc6cafd294c7d82f29370ae3baa00ef823479fd5cad9c6e
19.76 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
19.91 - File hash check (-42) 69f0db2e0a25d17dafc6cafd294c7d82f29370ae3baa00ef823479fd5cad9c6e

**Comment by dicemanproductionz** [comment]
Issue fixed found the download on the discord channel and manually added it to the download folder before retriggering wabbajack
